url: "https://www.bridgetownrb.com"
permalink: simple
timezone: America/Los_Angeles

# components_dir:
#   - ../shared/components
#   - _components

collections:
  docs:
    output: true
    permalink: /:collection/:path
    sort_by: order
    name: Documentation

defaults:
  - scope:
      path: ""
    values:
      image: /images/bridgetown-logo-twitter-card.jpg
  - scope:
      path: _docs
    values:
      layout: docs
  - scope:
      path: _posts
    values:
      layout: post
      category: news
  - scope:
      path: _posts/drafts
    values:
      published: false

pagination:
  enabled: true

# Environment-specific settings
development:
  unpublished: true
