url: "https://www.bridgetownrb.com"
permalink: simple
timezone: America/Los_Angeles

content_engine: resource

collections:
  docs:
    output: true
    permalink: "/:collection/:path.*"
    sort_by: order
    name: Documentation
    foo: bar

pagination:
  enabled: true

# Environment-specific settings
development:
  unpublished: true

svg:
  optimize: true
